### ISSUE TITLE
Update specs to allow non-local cassette recordings

### ISSUE THREAD

**Issue by aaronklaassen** [unsplash/unsplash_rb#38]
Currently spec_helper has configuration that points at an instance of Unsplash running on localhost. Obviously that doesn't work for most people. 😅 Update that config and the cassettes so they record from api.unsplash.com. That way contributors can record their own cassettes.

**Comment by gustavosobral** [comment]
Do you need some help with this @aaronklaassen? May I can help. Not right now, but through the next week/weekend. What will be the approach? :smiley:

**Comment by aaronklaassen** [comment]
@gustavosobral I'm not 100% yet sure what approach to take. I'm definitely open to ideas if you've got them.

The easiest thing to do would be to create a dedicated app on production for running these test. The catch there of course is that that would mean committing its API keys (secret included). It would be heavily rate-limited, but even so I'd like to avoid that. I'm not worried about the keys currently committed in this repo because they don't - and never did - exist on production.

Another option is to make the keys configurable, like a regular gem usage. But then we probably have to dynamically insert the client-id into the cassette yml files via erb? That's kind of gross too, you know?

Hm. The second option here might work (without the erb hack) as long as VCR isn't matching requests on the `Authorization` header.

**Comment by gustavosobral** [comment]
Uhhm, I understood. I think that based on convenience for new comers, the first approach is better. It will be just fork the repo and all credentials for tests will be included. But what about the security to share these credentials here and the cost to have a test server just for this, you think that It's ok?

The second approach of allow the developer to insert their keys on the lib for tests It's good too, since they just store the client-id on cassetes, but will force them to have/create a account.

As you can see, I don't have any approach in mind :sweat_smile:

**Comment by aaronklaassen** [comment]
Months later, I realize that the right way to do this would be to change the VCR configuration so that by default it doesn't match requests on `host`: https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/default-cassette-options
