### ISSUE TITLE
Search return Unsplash::Error - orientation does not have a valid value

### ISSUE THREAD

**Issue by aguinefolleau** [unsplash/unsplash_rb#57]
#### Steps to Reproduce

`Unsplash::Photo.search('test', 1, 100)`

#### Observed Behaviour

API returns error `Unsplash::Error - orientation does not have a valid value`

#### Notes

I am a bit confused since the documentation doesn't seem to allow you to pass an orientation option in the search method, I tried it anyway passing `Unsplash::Photo.search('test',1, 100, orientation: 'landscape')` but it returned the same error.

**Comment by aaronklaassen** [comment]
@aguinefolleau Ah, you're right. The lib here is sending the blank orientation as part of the search request, when it should leave it off entirely.

I'll fix this here, but it's probably something we should handle API-side too, anyway.

The reason your example with the param failed is because it's not a named parameter. The correct method call is `Unsplash::Photo.search('test',1, 100, 'landscape')`

**Comment by aaronklaassen** [comment]
@aguinefolleau I just published `v1.5.5` that has this fix in it. :+1:

**Comment by aguinefolleau** [comment]
@aaronklaassen thank you, 

It works perfectly now ! and thank you as well for 'Unsplash::Photo.search('test',1, 100, 'landscape')' you should update [rubydoc](https://www.rubydoc.info/github/unsplash/unsplash_rb/) 👍
